name: CI

on: [push, pull_request]

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --release --all-features
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            target/release/fake-discord-embed
